server:
  port: 8888

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:mem:./h2/org2
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true